### ISSUE TITLE
uBeac.Web.Logging.MongoDB | BSON Serializers

### ISSUE THREAD

**Issue by mhmdtaherian** [ubeac/ubeac-api#144]
Right now the serialization on GUID and Decimal does not exist in WebLogging (Http Log). We should add the HttpLoging database like application and history database by using AddMongo.

**Comment by ilhesam** [comment]
https://github.com/ubeac/ubeac-api/commit/ccca373611b5985b2579422f03ec0a1be13ef45b

**Comment by ilhesam** [comment]
https://github.com/ubeac/ubeac-api/commit/ccca373611b5985b2579422f03ec0a1be13ef45b
