### ISSUE TITLE
uBeac.Web.Logging | Handle Errors in HTTP Logging

### ISSUE THREAD

**Issue by mhmdtaherian** [ubeac/ubeac-api#146]
Adding try/catch in creating http log and adding to the database to prevent any interruption in application normal process.

**Comment by ilhesam** [comment]
https://github.com/ubeac/ubeac-api/commit/944d1b7c8401593a5ad1dac04da0f5238a39aad9
https://github.com/ubeac/ubeac-api/commit/f4b2990911f5afdf740d5294065cd0d1350fbcc4
